name: DramaticDynamics
version: '${project.version}'
main: org.welfaresystems.dramaticdynamics.DramaticDynamics
api-version: '1.21'
authors: [ Jonathan Vazquez ]
description: Dynamics such as mod actions and magic wands to troll members that add a taste of fun to your server.
commands:
  getWand:
    description: "Get admin tool wand"
    usage: "/getWand"
    permission: getWand.wand
    permission-message: "You do not have permission to execute this command"
  getMace:
    description: "Get admin tool mace"
    usage: "/getMace"
    permission: getMace.mace
    permission-message: "You do not have permission to execute this command"
permissions:
  getWand.wand:
    default: op
  getMace.mace:
    default: op